development:
  # uri: mongodb://dev:Nearnote12@ds035997.mongolab.com:35997/near_io_dev
  uri: mongodb://staging:Nearnote12@ds039007.mongolab.com:39007/heroku_app8128986
  # database: near_io_dev
  database: app4487356
  logger: true

test:
  host: localhost
  database: nn_api_test

# set these environment variables on your prod server
production:
  uri: mongodb://staging:Nearnote12@ds039007.mongolab.com:39007/heroku_app8128986
  database: app4487356
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019